In [2]:
import numpy as np

In [3]:
x = np.array([10,20,40,30,50,25,30,60])
x

array([10, 20, 40, 30, 50, 25, 30, 60])

In [4]:
x.dtype

dtype('int64')

In [5]:
x.shape

(8,)

In [6]:
x.ndim

1

In [7]:
x.size

8

In [8]:
x[0]

np.int64(10)

In [9]:
x[4]

np.int64(50)

In [10]:
q=x.astype(float)
q

array([10., 20., 40., 30., 50., 25., 30., 60.])

In [11]:
#multidimensional
a=np.array([[10,30,40,60],[20,50,70,90]])
a

array([[10, 30, 40, 60],
       [20, 50, 70, 90]])

In [12]:
a.dtype

dtype('int64')

In [13]:
a.shape

(2, 4)

In [14]:
a.ndim

2

In [15]:
a.size

8

In [16]:
a[0]

array([10, 30, 40, 60])

In [17]:
a[1][0]

np.int64(20)

In [18]:
a.astype(float)

array([[10., 30., 40., 60.],
       [20., 50., 70., 90.]])

In [19]:
# another type of multidimensional
z=np.array([[[2,3,4,5]]])
z

array([[[2, 3, 4, 5]]])

In [20]:
z.ndim

3

In [21]:
z.shape

(1, 1, 4)

Bigger array

In [22]:
y=np.array([
[
[1,3,6,7],[4,5,2,0],[2,5,1,8]
],
[
[2,3,1,5],[5,1,0,3],[8,6,7,0]
],
[
[6,0,3,5],[4,6,0,2],[5,2,0,3]
]
])
y

array([[[1, 3, 6, 7],
        [4, 5, 2, 0],
        [2, 5, 1, 8]],

       [[2, 3, 1, 5],
        [5, 1, 0, 3],
        [8, 6, 7, 0]],

       [[6, 0, 3, 5],
        [4, 6, 0, 2],
        [5, 2, 0, 3]]])

In [23]:
y.astype(float)

array([[[1., 3., 6., 7.],
        [4., 5., 2., 0.],
        [2., 5., 1., 8.]],

       [[2., 3., 1., 5.],
        [5., 1., 0., 3.],
        [8., 6., 7., 0.]],

       [[6., 0., 3., 5.],
        [4., 6., 0., 2.],
        [5., 2., 0., 3.]]])

In [24]:
y.ndim

3

In [25]:
y.shape

(3, 3, 4)

In [26]:
y.size

36

In [27]:
y[1,1,2]

np.int64(0)

In [28]:
y[2,0]

array([6, 0, 3, 5])

In [29]:
y[0]

array([[1, 3, 6, 7],
       [4, 5, 2, 0],
       [2, 5, 1, 8]])

filling arrays

In [30]:
a = np.full((3,4,5),10)
a

array([[[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]],

       [[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]])

In [31]:
a.ndim

3

zeros and ones

In [32]:
a_zero = np.zeros((4,3))
a_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
a_one = np.ones((5,3))
a_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
a_one = np.ones((2,5,3))
a_one

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
a_one.ndim

3

In [36]:
# empty 
e = np.empty((4,4))
e

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [37]:
e = np.empty((3,6))
e

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [1.29060871e-306, 6.23055651e-307, 1.06811422e-306,
        3.56043054e-307, 1.37961641e-306, 1.11257852e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306, 2.22522597e-306, 8.01097889e-307]])

In [38]:
e = np.empty((3,3))
e

array([[4.67296746e-307, 1.69121096e-306, 6.23047842e-307],
       [2.22526399e-307, 6.23053614e-307, 7.56592338e-307],
       [9.34588061e-307, 9.34531022e-307, 3.62651150e-317]])

In [39]:
# random
b_random = np.random.random((2,2))
b_random

array([[0.14707518, 0.66079848],
       [0.1740276 , 0.73234364]])

In [40]:
b_random.ndim

2

In [41]:
b_random.size

4

In [42]:
b = np.random.random((4,5))
b

array([[0.71536968, 0.78002132, 0.86045046, 0.55513898, 0.48125702],
       [0.13525161, 0.76073366, 0.30165824, 0.03377011, 0.50189161],
       [0.9658197 , 0.67025871, 0.21092249, 0.59305881, 0.92486044],
       [0.33260435, 0.50667328, 0.21613667, 0.95821437, 0.659433  ]])

In [43]:
b.ndim

2

In [44]:
b.size

20

In [45]:
b = np.random.random((3,4))
b

array([[0.30463832, 0.5171504 , 0.00887384, 0.90602818],
       [0.55110196, 0.57684541, 0.67795591, 0.51586737],
       [0.15917422, 0.05136233, 0.04266434, 0.19401833]])

In [46]:
b.ndim

2

In [47]:
b.size

12

Ranges

In [48]:
# arange
a_arange = np.arange(10,50,5)
a_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

In [49]:
a = np.arange(5,80,6)
a

array([ 5, 11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77])

In [50]:
#linspace
b_linspace = np.linspace(0,50,2)
b_linspace

array([ 0., 50.])

In [51]:
b_linspace.ndim

1

In [52]:
b_linspace.size

2

In [53]:
b_linspace1 = np.linspace(0,50,30)
b_linspace1

array([ 0.        ,  1.72413793,  3.44827586,  5.17241379,  6.89655172,
        8.62068966, 10.34482759, 12.06896552, 13.79310345, 15.51724138,
       17.24137931, 18.96551724, 20.68965517, 22.4137931 , 24.13793103,
       25.86206897, 27.5862069 , 29.31034483, 31.03448276, 32.75862069,
       34.48275862, 36.20689655, 37.93103448, 39.65517241, 41.37931034,
       43.10344828, 44.82758621, 46.55172414, 48.27586207, 50.        ])

In [54]:
b_linspace1.size

30

In [55]:
b_linspace2 = np.linspace(0,50,25, dtype = int)
b_linspace2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 50])

In [56]:
l = np.linspace(10,60,20)
l

array([10.        , 12.63157895, 15.26315789, 17.89473684, 20.52631579,
       23.15789474, 25.78947368, 28.42105263, 31.05263158, 33.68421053,
       36.31578947, 38.94736842, 41.57894737, 44.21052632, 46.84210526,
       49.47368421, 52.10526316, 54.73684211, 57.36842105, 60.        ])

In [57]:
l.size

20

In [58]:
l2 = np.linspace(5,80,30, dtype = int)
l2

array([ 5,  7, 10, 12, 15, 17, 20, 23, 25, 28, 30, 33, 36, 38, 41, 43, 46,
       48, 51, 54, 56, 59, 61, 64, 67, 69, 72, 74, 77, 80])

identity matrix

In [59]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

math functions

In [63]:
ab = np.array([10,30,20,45,15,40,55])
ab

array([10, 30, 20, 45, 15, 40, 55])

In [64]:
#exponential
np.exp(ab)

array([2.20264658e+04, 1.06864746e+13, 4.85165195e+08, 3.49342711e+19,
       3.26901737e+06, 2.35385267e+17, 7.69478527e+23])

In [65]:
#sin 
np.sin(ab)

array([-0.54402111, -0.98803162,  0.91294525,  0.85090352,  0.65028784,
        0.74511316, -0.99975517])

In [66]:
np.cos(ab)

array([-0.83907153,  0.15425145,  0.40808206,  0.52532199, -0.75968791,
       -0.66693806,  0.02212676])

In [67]:
np.tan(ab)

array([  0.64836083,  -6.4053312 ,   2.23716094,   1.61977519,
        -0.8559934 ,  -1.11721493, -45.18308791])

In [68]:
np.log(ab)

array([2.30258509, 3.40119738, 2.99573227, 3.80666249, 2.7080502 ,
       3.68887945, 4.00733319])

In [69]:
np.sqrt(ab)

array([3.16227766, 5.47722558, 4.47213595, 6.70820393, 3.87298335,
       6.32455532, 7.41619849])

Aggregate Functions

In [70]:
ab.sum()

np.int64(215)

In [71]:
ab.min()

np.int64(10)

In [72]:
ab.max()

np.int64(55)

In [73]:
ab.mean()

np.float64(30.714285714285715)

In [74]:
np.median(ab)

np.float64(30.0)

In [75]:
# standard deviation
np.std(ab)

np.float64(15.452362609131383)

In [76]:
xyz = np.array([
[
[2,4,6,8,0],[1,3,5,7,0],[1,2,3,4,5],[6,7,8,9,0]
],
[
[5,3,7,4,8],[0,4,5,7,3],[3,8,3,4,2],[5,6,3,8,4]
],
[
[9,3,5,7,2],[8,2,6,3,0],[6,9,2,5,0],[2,6,4,2,9]
]
])
xyz

array([[[2, 4, 6, 8, 0],
        [1, 3, 5, 7, 0],
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]],

       [[5, 3, 7, 4, 8],
        [0, 4, 5, 7, 3],
        [3, 8, 3, 4, 2],
        [5, 6, 3, 8, 4]],

       [[9, 3, 5, 7, 2],
        [8, 2, 6, 3, 0],
        [6, 9, 2, 5, 0],
        [2, 6, 4, 2, 9]]])

In [77]:
xyz.sum()

np.int64(263)

In [78]:
xyz.min()

np.int64(0)

In [79]:
xyz.max()

np.int64(9)

In [80]:
xyz.mean()

np.float64(4.383333333333334)

In [81]:
np.median(xyz)

np.float64(4.0)

In [82]:
np.std(xyz)

np.float64(2.640023148046665)

Array index task

In [85]:
ar = np.arange(1,8,5)
ar

array([1, 6])

In [87]:
a = np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [91]:
x = np.array([
[
[1,2,3,4],[4,5,6,2],[0,9,7,9]
],
[
[6,4,6,2],[2,0,8,1],[7,4,6,2]
]
])
x

array([[[1, 2, 3, 4],
        [4, 5, 6, 2],
        [0, 9, 7, 9]],

       [[6, 4, 6, 2],
        [2, 0, 8, 1],
        [7, 4, 6, 2]]])

In [94]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:
y = np.ones(8)
y

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
ab = np.linspace(1,100,6)
ab

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [110]:
w = np.identity(4)
w

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [120]:
#create 1d array with first,middle,last numbers
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [124]:
a[0],a[2],a[4]

(np.int64(1), np.int64(3), np.int64(5))

In [142]:
#create 2d array with 2nd row 3rd column print
qwe = np.array([
[
[1,2,3,4],[4,5,6,7],[2,5,9,0]
],
[
[9,4,0,5],[9,4,1,0],[0,6,2,8]
]
])
qwe

array([[[1, 2, 3, 4],
        [4, 5, 6, 7],
        [2, 5, 9, 0]],

       [[9, 4, 0, 5],
        [9, 4, 1, 0],
        [0, 6, 2, 8]]])

In [143]:
qwe.ndim

3

In [150]:
# last column
qwe[1,:,-1]

array([5, 0, 8])

In [151]:
# 2nd block 1st column
qwe[1,:,-3]

array([4, 4, 6])

In [145]:
qwe[0,1,2]

np.int64(6)

In [146]:
#print 1st row
qwe[0]

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 5, 9, 0]])

In [147]:
#print last row
qwe[1,2]

array([0, 6, 2, 8])

In [148]:
op= np.array([[1,2,3,4],[4,5,6,7],[2,5,9,0]])
op[:,-1]

array([4, 7, 0])

In [49]:
#array reshaping
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [6]:
a_1 = np.array([10,49,32,50,12,30,54,28])
print(a_1.reshape(2,4))

[[10 49 32 50]
 [12 30 54 28]]


In [7]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a.reshape(4))

[1 2 3 4]


In [10]:
a1 = np.array([[29,45,90,21],[23,78,30,45]])
print(a1.reshape(8))

[29 45 90 21 23 78 30 45]


In [12]:
#random module
np.random.seed(0)
print(np.random.rand(5))
print(np.random.randint(1,10,5))
print(np.random.randn(5))
print(np.random.choice([10,20,30],5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[6 3 5 8 7]
[-0.05503512 -0.10731045  1.36546718 -0.09769572 -2.42595457]
[20 20 10 20 10]


In [13]:
np.random.seed(0)
print(np.random.rand(4))
print(np.random.randint(1,30,6))
print(np.random.randn(4))
print(np.random.choice([12,14,16,18,20],8))


[0.5488135  0.71518937 0.60276338 0.54488318]
[10 20 22 19  5 24]
[ 1.26611853 -0.50587654  2.54520078  1.08081191]
[14 12 14 20 18 12 18 12]


In [14]:
#array iterating
import numpy as np
a = np.array([10,20,30])
for i in a:
    print(i)


10
20
30


In [15]:
a2 = np.array([28,49,27,59,79,90])
for i in a2:
    print(i)

28
49
27
59
79
90


In [16]:
import numpy as np
a = np.array([[1,2],[3,4]])
for i in np.nditer(a):
    print(i)

1
2
3
4


In [18]:
a_2 = np.array([[20,30,40,50],[25,35,45,55]])
for i in np.nditer(a_2):
    print(i)

20
30
40
50
25
35
45
55


Joining Arrays

In [48]:
#concatenate
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
print(np.concatenate((a,b)))

[1 2 3 4]


In [20]:
aq = np.array([27,40,39])
bq = np.array([30,48,59])
print(np.concatenate((aq,bq)))

[27 40 39 30 48 59]


In [43]:
#stack
import numpy as np
a = ([2,4,6,8,10,12])
b = ([3,7,9,13,15,18])
print(np.stack((a,b)))

[[ 2  4  6  8 10 12]
 [ 3  7  9 13 15 18]]


In [46]:
#vertical stack
print(np.vstack((a,b)))

[[ 2  4  6  8 10 12]
 [ 3  7  9 13 15 18]]


In [47]:
#horizontal stack
print(np.hstack((a,b)))

[ 2  4  6  8 10 12  3  7  9 13 15 18]


In [25]:
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [26]:
#splitting arrays
import numpy as np
a = np.array([10,20,30,40])
print(np.array_split(a,2))

[array([10, 20]), array([30, 40])]


In [27]:
import numpy as np 
a = np.array([1, 2, 3, 4, 5]) 
print(np.array_split(a, 3))

[array([1, 2]), array([3, 4]), array([5])]


In [29]:
c = np.array([30,20,10,40,50,60])
print(np.array_split(c,3))

[array([30, 20]), array([10, 40]), array([50, 60])]


In [30]:
#searching arrays
import numpy as np
a = np.array([10,20,30,20])
print(np.where(a==20))

(array([1, 3]),)


In [31]:
import numpy as np
a = np.array([5,8,10,15])
print(np.where(a>8))

(array([2, 3]),)


In [32]:
c1 = np.array([24,59,30,27,49,10])
print(np.where(c1==49))

(array([4]),)


In [33]:
#sorting arrays
import numpy as np
a = np.array([40,10,30,20])
print(np.sort(a))

[10 20 30 40]


In [34]:
import numpy as np 
a = np.array(["Banana", "Apple", "Orange"]) 
print(np.sort(a))

['Apple' 'Banana' 'Orange']


In [35]:
d = np.array([20,38,10,37])
print(np.sort(d))

[10 20 37 38]


In [36]:
#filter arrays
import numpy as np
a = np.array([10,20,30,40,50])
print(a[a>25])

[30 40 50]


In [37]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a[a%2==0])

[2 4 6]


In [38]:
e = np.array([50,60,30,10,80])
print(e[e>40])

[50 60 80]


In [42]:
e1 = np.array([50,60,30,10,80,5,7,70])
print(e1[e1%3!=0])

[50 10 80  5  7 70]


In [50]:
#universal functions
import numpy as np
a = np.array([1,4,9])
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.abs(a))

[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[0.         1.38629436 2.19722458]
[ 0.84147098 -0.7568025   0.41211849]
[ 0.54030231 -0.65364362 -0.91113026]
[ 1.55740772  1.15782128 -0.45231566]
[1 4 9]


In [51]:
fd = np.array([5,2,8,6])
print(np.sqrt(fd))
print(np.exp(fd))
print(np.log(fd))
print(np.sin(fd))
print(np.cos(fd))
print(np.tan(fd))
print(np.abs(fd))

[2.23606798 1.41421356 2.82842712 2.44948974]
[ 148.4131591     7.3890561  2980.95798704  403.42879349]
[1.60943791 0.69314718 2.07944154 1.79175947]
[-0.95892427  0.90929743  0.98935825 -0.2794155 ]
[ 0.28366219 -0.41614684 -0.14550003  0.96017029]
[-3.38051501 -2.18503986 -6.79971146 -0.29100619]
[5 2 8 6]


In [52]:
#aggregration functions
import numpy as np
a = np.array([3,7,2,9,4])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))

25
5.0
4.0
2.6076809620810595
6.8
2
9
2
3


In [53]:
az = np.array([4,9,2,7])
print(np.sum(az))
print(np.mean(az))
print(np.median(az))
print(np.std(az))
print(np.var(az))
print(np.min(az))
print(np.max(az))
print(np.argmin(az))
print(np.argmax(az))

22
5.5
5.5
2.692582403567252
7.25
2
9
2
1


In [55]:
#axis concept
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[5 7 9]
[ 6 15]


In [57]:
ax = np.array([[9,3,2,4],[3,2,8,7]])
print(np.sum(ax,axis=0))
print(np.sum(ax,axis=1))

[12  5 10 11]
[18 20]
