In [1]:
#Create a NumPy array containing the numbers 10, 20, 30, 40, 50.
import numpy as np
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [38]:
#Create a NumPy array containing numbers from 1 to 10.
arry = np.arange(1,11)
arry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
#Create an array of even numbers between 1 and 20
ary = np.arange(2,21,2)
ary

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
#Create an array of odd numbers between 1 and 20.
aryy = np.arange(1,20,2)
aryy

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
#Create a NumPy array containing five zeros.
a_ry = np.zeros(5)
a_ry

array([0., 0., 0., 0., 0.])

In [14]:
#Create a NumPy array containing six ones.
a_rry = np.ones(6)
a_rry

array([1., 1., 1., 1., 1., 1.])

In [17]:
#Create a 2 × 3 NumPy array
ab = np.array([[2,6,9],[4,7,1]])
ab

array([[2, 6, 9],
       [4, 7, 1]])

In [18]:
#Create a 3 × 3 NumPy array containing numbers from 1 to 9.
a_b = np.array([[1,2,3],[4,5,6],[7,8,9]])
a_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
#Create a 3 × 3 NumPy array containing numbers from 1 to 9.
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
#Create an array of five equally spaced numbers between 0 and 10
a_r = np.linspace(0,10,5)
a_r

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
#Create an array containing the numbers 5, 10, 15, 20, 25 and print the first element.
arr_y = np.array([5,10,15,20,25])
arr_y[0]

np.int64(5)

In [48]:
#Create an array containing 10, 20, 30, 40, 50 and print the last three elements.
x = np.array([10,20,30,40,50])
x[-3:]

array([30, 40, 50])

In [24]:
#Create an array from 1 to 10 and print only the numbers greater than 5.
z = np.arange(1,11)
print(z[z>5])

[ 6  7  8  9 10]


In [51]:
#Create an array from 1 to 10 and print only the even numbers
xy = np.arange(1,11)
print(xy[xy % 2 == 0])

[ 2  4  6  8 10]


In [52]:
#Create an array [10, 20, 30, 40, 50] and find its maximum value.
az = np.array([10,20,30,40,50])
az.max()

np.int64(50)

In [53]:
#Create an array [10, 20, 30, 40, 50] and find its minimum value.
a_z = np.array([10,20,30,40,50])
a_z.min()

np.int64(10)

In [54]:
#Create an array [10, 20, 30, 40, 50] and calculate its sum
x_y = np.array([10,20,30,40,50])
x_y.sum()

np.int64(150)

In [55]:
#Create an array [10, 20, 30, 40, 50] and calculate its mean
a_y = np.array([10,20,30,40,50])
a_y.mean()

np.float64(30.0)

In [56]:
#Create an array [5, 2, 8, 1, 9] and sort it in ascending order.
import numpy as np
arry = np.array([5,2,8,1,9])
np.sort(arry)

array([1, 2, 5, 8, 9])

In [57]:
#Create an array [10, 20, 30, 40, 50] and find the position of its maximum value
import numpy as np
ary = np.array([10,20,30,40,50])
np.argmax(ary)

np.int64(4)

In [58]:
#Create an array [10, 20, 30, 40, 50] and find the position of its minimum value.
import numpy as np
ary = np.array([10,20,30,40,50])
np.argmin(ary)

np.int64(0)