In [2]:
#Create a NumPy array containing 10, 20, 30, 40, 50. Display the array, its shape, data type, size of each element, and total memory used.
import numpy as np
a =np.array ([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [65]:
# data type
a.dtype

dtype('int64')

In [66]:
# shape
a.shape

(5,)

In [68]:
# size of each element
a.size

5

In [67]:
# total memory used
a.nbytes

40

In [7]:
#Create a 3 * 4 array containing the numbers from 1 to 12. Display the second and third rows.
ar = np.arange(1,13).reshape(3,4)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
# display second and third rows
ar[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
#Create an array containing the numbers from 1to 12 and convert it into a 3 × 4 array
ary = np.arange(1,13).reshape(3,4)
ary

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# Create two arrays containing [10, 20, 30] and [40, 50, 60]. Combine them so that the result contains two rows
a1 = np.array([10,20,30])
a2 = np.array([40,50,60])
np.vstack((a1,a2))

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
#Divide the array [10, 20, 30, 40, 50] into three smaller arrays
arry = np.array([10,20,30,40,50])
np.array_split(arry,3)

[array([10, 20]), array([30, 40]), array([50])]

In [12]:
#Given the array [5, 10, 15, 20, 25, 30], display the positions of all elements greater than 15
ab = np.array([5,10,15,20,25,30])
np.where(ab>15)

(array([3, 4, 5]),)

In [13]:
# Given the array [12, 5, 20, 8, 30, 15], display only the values between 10 and 25.
a_b = np.array([12,5,20,8,30,15])
a_b[(a_b>=10)&(a_b<=25)]

array([12, 20, 15])

In [14]:
# Given the array [4, 9, 16, 25], calculate the square root of every element
import numpy as np
arry = np.array([4,9,16,25])
np.sqrt(arry)

array([2., 3., 4., 5.])

In [15]:
# Given the array [1, 2, 3, 4], calculate the exponential value and natural logarithm of every element
import numpy as np
arry = np.array([1,2,3,4])
np.exp(arry)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [70]:
# natural logarithm
np.log(arry)

array([3.55534806, 2.30258509, 4.09434456, 3.21887582, 1.60943791,
       3.80666249])

In [17]:
# Given the array [10, 20, 30, 40, 50], find the total, average, median,standard deviation, variance, smallest value, and largest value.
import numpy as np
a = np.array([10,20,30,40,50])
np.sum(a)

np.int64(150)

In [71]:
# average
np.average(a)

np.float64(30.0)

In [73]:
# median
np.median(a)

np.float64(30.0)

In [74]:
# standard deviation
np.std(a)

np.float64(14.142135623730951)

In [75]:
# variance
np.var(a)

np.float64(200.0)

In [76]:
# smallest value
np.min(a)

np.int64(10)

In [77]:
# largest value
np.max(a)

np.int64(50)

In [24]:
# Given the array [10, 20, 5, 40, 15], find the positions of the smallest and largest elements
ar_y = np.array([10,20,5,40,15])
np.argmin(ar_y)

np.int64(2)

In [78]:
# position of largest element
np.argmax(ar_y)

np.int64(3)

In [29]:
# Given the array [[2, 4, 6],[8, 10, 12]] Find the sum of the values in each row and the sum of the values in each column.
arra_y =np.array([[2, 4, 6],
         [8, 10, 12]])
np.sum(arra_y,axis = 0)

array([10, 14, 18])

In [79]:
#Find the sum of the values in each row
np.sum(arra_y,axis = 1)

array([12, 30])

In [31]:
# Create an array containing [10, 20, 30, 40]. Create a separate copy and a view of the array. Modify the arrays and observe the effect on the original array.
import numpy as np
a = np.array([10,20,30,40])
b= a.copy()
b[1] = 90
print(a)
print(b)


[10 20 30 40]
[10 90 30 40]


In [80]:
# view 
a1 = np.array([10,20,30,40])
b1 = a1.view()
b1[1] = 90
print(a1)
print(b1)

[10 90 30 40]
[10 90 30 40]


In [37]:
# Generate five random decimal numbers, five random integers between 1 and 20, and five values from the list [10, 20, 30, 40] 
np.random.randint(1,20)
np.random.choice([10,20,30,40])
np.random.rand(5)


array([0.26277035, 0.88116307, 0.17043264, 0.41966083, 0.11971103])

In [42]:
#Given the array:[[1, 2, 3], [4, 5, 6]] Print every element one by one, then convert the array into a one-dimensional array
import numpy as np
a = np.array([[1, 2, 3],
    [4, 5, 6]])
for i in np.nditer(a):
   print(i)

1
2
3
4
5
6


In [81]:
#  convert the array into a one-dimensional array
a.flatten()

array([10, 20, 30, 40, 50])

In [47]:
# Given the array [35, 10, 60, 25, 5, 45] , arrange the elements in ascending order
import numpy as np
arry = np.array([35,10,60,25,5,45])
np.sort(arry)

array([ 5, 10, 25, 35, 45, 60])

In [82]:
# descending order
import numpy as np
arry = np.array([35,10,60,25,5,45])
np.sort(arry)[::-1]

array([60, 45, 35, 25, 10,  5])

In [52]:
# Given the array ["Mango", "Apple", "Grapes", "Banana", "Orange"], arrange the elements in alphabetical order
fruits = np.array(["Mango","Apple","Grapes","Banana","Orange"])
np.sort(fruits)

array(['Apple', 'Banana', 'Grapes', 'Mango', 'Orange'], dtype='<U6')

In [54]:
# Create a NumPy array containing [10, 20, 30, 40, 50, 60]. Divide the array into four smaller arrays.
num = np.array([10,20,30,40,50,60])
np.array_split(num,4)

[array([10, 20]), array([30, 40]), array([50]), array([60])]

In [57]:
# Create two arrays containing [1, 2, 3] and [4, 5, 6]. Combine them horizontally so that the result is a single row containing all six elements.
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [62]:
# Create a NumPy array containing [10, 20, 30, 40, 50]. Perform addition, subtraction, multiplication, division, and squaring operations on the array
import numpy as np
a = np.array([10,20,30,40,50])
print(a + 5)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

[15 25 35 45 55]
[ 8 18 28 38 48]
[ 20  40  60  80 100]
[ 5. 10. 15. 20. 25.]
[ 100  400  900 1600 2500]


In [64]:
import numpy as np
a = np.array([10,20,30,40,50])
b = np.array([2,4,6,8,10])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[12 24 36 48 60]
[ 8 16 24 32 40]
[ 20  80 180 320 500]
[5. 5. 5. 5. 5.]
[              100            160000         729000000     6553600000000
 97656250000000000]
